services:
  - type: web
    name: mcp-fastmcp-backend
    runtime: python # use Render's Python runtime
    buildCommand: |
      uv sync                # fast, lock-file based install
    plan: free
